#!/usr/bin/env bash

# Run PHPCS
ROOT_DIR="$(pwd)/"
LIST=$( git diff --name-only --cached --diff-filter=ACM -- '*.php' '*.inc' '*.profile' '*.module' '*.install' '*.profile' '*.test' '*.theme' '*.js' '*.css' '*.info' '*.txt' '*.md')
PHPCS_BIN=bin/phpcs

if [ ! -f $PHPCS_BIN ];
  then
    echo "WARNING: PHP Code Sniffer was not found. This commit might include coding standards violations. You can fix this by ensuring that composer has correctly installed it's dev dependencies including a symlink in the bin folder to the phpcs package in vendor."
    exit 1
  else
    echo "Sniffing staged files via PHP Code Sniffer."
fi

if [ ! -z "$LIST" ];
  then
    # Classic sniffer.
    $PHPCS_BIN --standard=${ROOT_DIR}/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml ${LIST} --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt,md
    # Best Practice.
    $PHPCS_BIN --standard=${ROOT_DIR}/vendor/drupal/coder/coder_sniffer/DrupalPractice/ruleset.xml ${LIST} --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt,md
fi

e=$?

exit $e
